@baseURL = http://127.0.0.1:8000

###
# @name allStates
Get {{baseURL}}/api/states

###
# @name createState
POST {{baseURL}}/api/states
Content-Type: application/json

{
    "name": "Piaui",
    "abbreviation": "PI"
}

###
# @name getOne
GET {{baseURL}}/api/states/2

###
# @name deleteOne
DELETE {{baseURL}}/api/states/4