@baseURL = http://127.0.0.1:8000

###
# @name allStates
Get {{baseURL}}/api/states

###
# @name createState
POST {{baseURL}}/api/states
Content-Type: application/json

{
    "name": "Ceara",
    "abbreviation": "CE"
}