@baseURL = http://127.0.0.1:8000

###
# @name allStates
Get {{baseURL}}/api/states

###
# @name createState
POST {{baseURL}}/api/states
Content-Type: application/json

{
    "name": "Distrito Federal",
    "abbreviation": "DF"
}

###
# @name getOneState
GET {{baseURL}}/api/states/7

###
# @name deleteOneState
DELETE {{baseURL}}/api/states/4

###
# @name updateOneState
PUT {{baseURL}}/api/states/5
Content-Type: application/json

{
    "name": "PIAUI",
    "abbreviation": "PI"
}

###
# @name allCities
Get {{baseURL}}/api/cities?filters=[{"property: "state__id", "value": 5, "stage": 1}]

###
# @name createCity
POST {{baseURL}}/api/cities
Content-Type: application/json

{
    "name": "Aparecida",
    "state_id": 6
}

###
# @name getOneCity
GET {{baseURL}}/api/cities/2

###
# @name updateOneCity
PUT {{baseURL}}/api/cities/2
Content-Type: application/json

{
    "name": "Aparecida do Goias"
}

###
# @name deleteOneCity
DELETE {{baseURL}}/api/cities/2