@baseURL = http://127.0.0.1:8000

###
# @name allCities
Get {{baseURL}}/api/cities?filters=[{"property": "state__id", "value": 6, "stage": 1}]

###
# @name createCity
POST {{baseURL}}/api/cities
Content-Type: application/json

{
    "name": "Aparecida",
    "state_id": 6
}

###
# @name getOneCity
GET {{baseURL}}/api/cities/2

###
# @name updateOneCity
PUT {{baseURL}}/api/cities/2
Content-Type: application/json

{
    "name": "Aparecida do Goias"
}

###
# @name deleteOneCity
DELETE {{baseURL}}/api/cities/2