@baseURL = http://127.0.0.1:8000
@resource = packages

###
# @name all
GET {{baseURL}}/api/{{resource}}

###
# @name create
POST {{baseURL}}/api/{{resource}}
Content-Type: application/json

{
    "sender_id": 1,
    "destination_id": 2,
    "weight": 1.5,
    "volume": 5
}

###
# @name getOne
GET {{baseURL}}/api/{{resource}}/2


###
# @name update
PUT {{baseURL}}/api/{{resource}}/1
Content-Type: application/json

{
    "delivery_state": 2
}

###
# @name deleteOne
DELETE {{baseURL}}/api/{{resource}}/1 

###
# @name RegisterLog
POST {{baseURL}}/api/{{resource}}/4343eb93/log
Content-Type: application/json

{
    "city_id": 2
}