# Generated by Django 3.2.1 on 2021-05-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracker.city')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.person')),
                ('fantasy_name', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=11, unique=True, verbose_name='Cadastro Nacional de Pessoa Juridica')),
            ],
            bases=('tracker.person',),
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.person')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='Cadastro de Pessoa Fisica')),
            ],
            bases=('tracker.person',),
        ),
    ]
