# Generated by Django 3.2 on 2021-04-30 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='Cadastro de Pessoa Fisica')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracker.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('fantasy_name', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=11, unique=True, verbose_name='Cadastro Nacional de Pessoa Juridica')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracker.city')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
