# Generated by Django 3.2.1 on 2021-05-06 18:22

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_packagecontainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=tracker.models.City, related_name='+', to='tracker.city')),
                ('package_container', models.ForeignKey(on_delete=tracker.models.PackageContainer, related_name='logs', to='tracker.packagecontainer')),
            ],
        ),
    ]
